services:
  - type: web
    name: mi-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: PORT
        value: 8000
