services:
  - type: web
    name: mi-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    repo: https://github.com/JeanDurango/API.git
    branch: main
